### ISSUE TITLE
no "Binary Internals Viewer"

### ISSUE THREAD

**Issue by tp7309** [amosshi/freeinternals#2]
It is very helpful to understand the structure of class file, So amazing tool!
I search author name which from "codeproject", then find this repo, Thank for your contribution^_^
I am confused about why not generate release file directly on github? And now only
"JavaClassViewer" can be downloaded, no "Binary Internals Viewer".

**Comment by amosshi** [comment]
I will.
- Will provide both downloads in release downloads
- Will update Java Class Viewer to JDK12

**Comment by tp7309** [comment]
Thanks.

**Comment by amosshi** [comment]
@tp7309  https://github.com/amosshi/freeinternals/releases/tag/biv.2.0 relased

**Comment by tp7309** [comment]
thank you.
